language: node_js
node_js:
- "8"
services:
- docker
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
  # Updating NPM to relevant version >= 3 on Node.JS LTS
- npm i -g npm@^3
- npm i -g brfs
script:
- npm run build:prod
sudo: required
addons:
  apt:
    packages:
    - sshpass
    - google-chrome-stable
after_success:
- mv dist survey-app
- tar -czf build.tgz survey-app
- export SSHPASS=$DEPLOY_PASS
- sshpass -e scp -o stricthostkeychecking=no build.tgz $DEPLOY_USER@$DEPLOY_HOST:./
- sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST ./deploy-build.sh